INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (1, 'admin', 'admin');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (2, 'Saulius', 'saulius');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (3, 'Karolis', 'karolis');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (4, 'Gintas', 'gintas');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (5, 'Olegas', 'olegas');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (6, 'Jurga', 'jurga');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (7, 'Domantas', 'domantas');


INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_ID) VALUES (1, 'nusivalyti batus', '2018-06-20 20:20:00', 4);
