INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (1, 'admin', 'admin', 'Reminderis nenustatytas'); //superuser
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (2, 'Saulius', 'saulius');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (3, 'Karolis', 'karolis');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (4, 'Gintas', 'gintas');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (5, 'Olegas', 'olegas');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (6, 'Jurga', 'jurga');
INSERT INTO TBL_USERS (USER_ID, USER_LOGIN, USER_PWD) VALUES (7, 'Domantas', 'domantas');


INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (1, 'nusivalyti batus', TO_DATE('2018/06/20 12:01:00', 'yyyy/mm/dd hh24:mi:ss'), 'Gintas');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (2, '12:00 - pas dantista!!', TO_DATE('2018/06/20 12:02:00', 'yyyy/mm/dd hh24:mi:ss'), 'Olegas');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (3, '11:30 - 13:30 -> PASKAITA!', TO_DATE('2018/06/20 12:03:00', 'yyyy/mm/dd hh24:mi:ss'), 'admin');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (4, 'Nupirkti duonos', TO_DATE('2018/06/20 12:04:00', 'yyyy/mm/dd hh24:mi:ss'), 'Karolis');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (5, 'Uzsakyti popieriaus', TO_DATE('2018/06/20 12:05:00', 'yyyy/mm/dd hh24:mi:ss'), 'admin');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (6, 'Mociutes gimtadienis. VALIOOOOOOOOOOO!!!!', TO_DATE('2018/06/20 12:06:00', 'yyyy/mm/dd hh24:mi:ss'), 'Domantas');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (7, 'Nusiskusti usus', TO_DATE('2018/06/20 12:07:00', 'yyyy/mm/dd hh24:mi:ss'), 'Jurga');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (8, '15:46 Isvesti suni i lauka!', TO_DATE('2018/06/20 12:08:00', 'yyyy/mm/dd hh24:mi:ss'), 'Domantas');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (9, '19:30 - perskambinti mamai', TO_DATE('2018/06/20 12:09:00', 'yyyy/mm/dd hh24:mi:ss'), 'Jurga');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (10, '16:30 - pasiimti vaikus is darzelio', TO_DATE('2018/06/20 12:10:00', 'yyyy/mm/dd hh24:mi:ss'), 'Saulius');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (11, '15:00 FUTBOLAS!!', TO_DATE('2018/06/20 12:11:00', 'yyyy/mm/dd hh24:mi:ss'), 'Gintas');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (12, '18:00 FUTBOLAS!!', TO_DATE('2018/06/20 12:12:00', 'yyyy/mm/dd hh24:mi:ss'), 'Karolis');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (13, '21:00 FUTBOLAS!!', TO_DATE('2018/06/20 12:13:00', 'yyyy/mm/dd hh24:mi:ss'), 'Saulius');
INSERT INTO TBL_REMINDERS (REMINDER_ID, REMINDER_NOTE, REMINDER_DATE, USER_LOGIN) VALUES (14, 'issivalyti dantis pries miega', TO_DATE('2018/06/20 12:14:00', 'yyyy/mm/dd hh24:mi:ss'), 'Olegas');